version: '3.3'
services:
  db:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: crud
    volumes: 
    - "/data/db"
    ports:
    - "27017:27017"
  
  frontend:
    build: ./frontend/
    container_name: frontend
    depends_on: 
    - "backend"
    environment:
      PORT: 3005
    ports:
    - "3005:3005"

  backend:
    build: ./backend/
    container_name: backend
    ports:
    - "5555:5555"
    environment:
      HOST: mongo_db
      SERVER_PORT: 5555
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
    depends_on:
    - "db"


  
  
