
services:
  db:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: crud
    volumes: 
    - "/data/db"
    ports:
    - "27017:27017"
  
  frontend:
    image: iahs5/book-store-client:1.3
    container_name: frontend
    depends_on: 
    - "backend"
    environment:
      VITE_PORT: 3005
      VITE_SERVER_PORT: 5555
      VITE_HOST: localhost
    ports:
    - "3005:3005"

  backend:
    image: iahs5/book-store-server:1.0
    container_name: backend
    ports:
    - "5555:5555"
    environment:
      HOST: mongo_db
      SERVER_PORT: 5555
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
    depends_on:
    - "db"


  
  
